//This file is generated by an external tool, and should not be manually edited.
var Badgelist = new Array(4);

    Badgelist[0] = new Badge("Github",
                             "https://github.com/CGordini",
                             "fa-github");

    Badgelist[1] = new Badge("Bitbucket",
                             "https://bitbucket.org/cgordini",
                             "fa-bitbucket");

    Badgelist[2] = new Badge("Blogspot",
                             "http://cgordini.blogspot.com/",
                             "fa-google");

    Badgelist[3] = new Badge("test4",
                             "https://github.com/CGordini",
                             "fa-fax");

