//This file is generated by an external tool, and should not be manually edited.
var Badgelist = new Array(4);

    Badgelist[0] = new Badge("My Github",
                             "https://github.com/CGordini",
                             "fa-github");

    Badgelist[1] = new Badge("My Bitbucket",
                             "https://bitbucket.org/cgordini",
                             "fa-bitbucket");

    Badgelist[2] = new Badge("My Blog",
                             "http://cgordini.blogspot.com/",
                             "fa-google");

    Badgelist[3] = new Badge("My Resume",
                             "App/Docs/Resume.pdf",
                             "fa-file-text");

    Badgelist[4] = new Badge("My References",
                             "App/Docs/References.pdf",
                             "fa-file-pdf-o");

    Badgelist[5] = new Badge("Email Me",
                             "mailto:cory.gordinier@gmail.com",
                             "fa-envelope-o");
