//This file is generated by an external tool, and should not be manually edited.
var Worksites = new Array(4);

    Worksites[0] = new Work("Software Engineer",
                                    "Thomson Reuters",
                                    "May",
                                    2014,
                                    "Current",
                                    2014,
                                    "Document Management System Development",
                                    "7322 Newman Blvd",
                                    "Dexter",
                                    "MI",
                                    3
                            );

    Worksites[1] = new Work("Accounting Development Intern",
                                    "Thomson Reuters",
                                    "May",
                                    2013,
                                    "August",
                                    2013,
                                    "Workpapers CS/Engagement",
                                    "7322 Newman Blvd",
                                    "Dexter",
                                    "MI",
                                    2
                            );

    Worksites[2] = new Work("Programming Intern",
                                    "Retail Me Not, Inc.",
                                    "May",
                                    2012,
                                    "August",
                                    2012,
                                    "Web Development",
                                    "301 Congress Ave #700",
                                    "Austin",
                                    "TX",
                                    1
                            );

    Worksites[3] = new Work("Programming Researcher",
                                    "University of Michigan EECS Department",
                                    "May",
                                    2011,
                                    "May",
                                    2012,
                                    "Software-Defined Radio development, in conjunction with Microsoft Research",
                                    "1301 Beal Ave",
                                    "Ann Arbor",
                                    "MI",
                                    0
                            );
    